"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const router_1 = __importDefault(require("./user/router"));
const router_2 = __importDefault(require("./pdf/router"));
const router_3 = __importDefault(require("./resource/router"));
const router_4 = __importDefault(require("./queries/router"));
const router_5 = __importDefault(require("./analytics/router"));
const router_6 = __importDefault(require("./auth/router"));
const router = express_1.default.Router();
router.use('/users', router_1.default);
router.use('/pdf', router_2.default);
router.use('/resources', router_3.default);
router.use('/queries', router_4.default);
router.use('/analytics', router_5.default);
router.use('/admin', router_6.default);
exports.default = router;
